<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
      DB::table('users')->insert([
          ['name' => 'test',
          'email' => 'test1@test.com',
          'age' => '25',
          'sex' => '0',
          'self_introduction' => '初めまして！私の名前はtestです',
          'password' => Hash::make('11111111'),
          ],
          ['name' => 'ジョブズ',
          'email' => 'user1@example.com',
          'age' => '30',
          'sex' => '0',
          'self_introduction' => 'ジョブズです',
          'password' => Hash::make('password123'),
          ],
          ['name' => 'ザッカーバーグ',
          'email' => 'user2@example.com',
          'age' => '43',
          'sex' => '1',
          'self_introduction' => 'ザッカーバーグです',
          'password' => Hash::make('password123'),
          ],
          ['name' => 'ジェフペゾフ',
          'email' => 'user3@example.com',
          'age' => '38',
          'sex' => '0',
          'self_introduction' => 'ジェフです',
          'password' => Hash::make('password123'),
          ],
          ['name' => 'イーロン',
          'email' => 'user4@example.com',
          'age' => '28',
          'sex' => '0',
          'self_introduction' => 'イーロンです',
          'password' => Hash::make('password123'),
          ],
          ['name' => 'リトル本田圭佑',
          'email' => 'user5@example.com',
          'age' => '6',
          'sex' => '0',
          'self_introduction' => 'リトル本田圭佑です',
          'password' => Hash::make('password123'),
          ],
          ['name' => '香川真司',
          'email' => 'user6@example.com',
          'age' => '36',
          'sex' => '0',
          'self_introduction' => '香川真司です',
          'password' => Hash::make('password123'),
          ],
          ['name' => 'ザッケローニ',
          'email' => 'user7@example.com',
          'age' => '46',
          'sex' => '0',
          'self_introduction' => '職業監督です',
          'password' => Hash::make('password123'),
          ],
          ['name' => '浜辺美波',
          'email' => 'user8@example.com',
          'age' => '21',
          'sex' => '0',
          'self_introduction' => '時の人、浜辺美波です',
          'password' => Hash::make('password123'),
          ],
          ['name' => '石原さとみ',
          'email' => 'user9@example.com',
          'age' => '31',
          'sex' => '0',
          'self_introduction' => '女優の石原さとみです',
          'password' => Hash::make('password123'),
          ],
          ['name' => '有村架純',
          'email' => 'user10@example.com',
          'age' => '29',
          'sex' => '0',
          'self_introduction' => '有村姉妹の妹です',
          'password' => Hash::make('password123'),
          ],
      ]);
    }
}
